window.Seed = (function () {
	const Teams =[
		
		{
		 id: 1,
		 Name: 'Leche Completa',
		 protein: 8,
		 Grasas_T: 8.4,
		 Grasas_S: 5.3,
		 Grasas_M: 2.4,
		 Grasas_P: 0.3,
		 Colesterol: 32,
		 CHO: 12,
		 Na: 0,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 2,
		 Name: 'Leche y Yogurt Descremado',
		 protein: 8,
		 Grasas_T: 3.2,
		 Grasas_S: 2.05,
		 Grasas_M: 1.15,
		 Grasas_P: 0.15,
		 Colesterol: 13.5,
		 CHO: 12,
		 Na: 2.5,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 3,
		 Name: 'Hortalizas y Vegetales',
		 protein: 2,
		 Grasas_T: 0,
		 Grasas_S: 0,
		 Grasas_M: 0,
		 Grasas_P: 0,
		 Colesterol: 0,
		 CHO: 5,
		 Na: 0.5,
		 Fibra: [0.5,2],
		 Unidad: 1,
		},
		{
		 id: 4,
		 Name: 'Frutas',
		 protein: 0,
		 Grasas_T: 0,
		 Grasas_S: 0,
		 Grasas_M: 0,
		 Grasas_P: 0,
		 Colesterol: 0,
		 CHO: 15,
		 Na: 'tr',
		 Fibra: [0.5,2],
		 Unidad: 1,
		},
		{
		 id: 5,
		 Name: 'Almidones, Cereales, Pan',
		 protein: 2,
		 Grasas_T: 0,
		 Grasas_S: 0,
		 Grasas_M: 0,
		 Grasas_P: 0,
		 Colesterol: 0,
		 CHO: 15,
		 Na: 0.5,
		 Fibra: [2,3],
		 Unidad: 1,
		},
		{
		 id: 6,
		 Name: 'Leguminosas',
		 protein: 3,
		 Grasas_T: 0,
		 Grasas_S: 0,
		 Grasas_M: 0,
		 Grasas_P: 0,
		 Colesterol: 0,
		 CHO: 0,
		 Na: 0,
		 Fibra: [1.5,5],
		 Unidad: 1,
		},
		{
		 id: 7,
		 Name: 'Huevo Completo',
		 protein: 7,
		 Grasas_T: 5.7,
		 Grasas_S: 1.7,
		 Grasas_M: 2,
		 Grasas_P: 0.5,
		 Colesterol: 252,
		 CHO: 0,
		 Na: 0,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 8,
		 Name: 'Carne (<10% y 17% grasa)',
		 protein: 7,
		 Grasas_T: 3.5,
		 Grasas_S: 1.35,
		 Grasas_M: 1.95,
		 Grasas_P: 0.25,
		 Colesterol: 26,
		 CHO: 0,
		 Na: 0,
		 Fibra:0,
		 Unidad: 1,
		},
		{
		 id: 9,
		 Name: 'Carne (27% grasa)',
		 protein: 7,
		 Grasas_T: 8.1,
		 Grasas_S: 3.2,
		 Grasas_M: 3.5,
		 Grasas_P: 0.5,
		 Colesterol: 26,
		 CHO: 0,
		 Na: 0,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 10,
		 Name: 'Pescado',
		 protein: 7,
		 Grasas_T: 1.8,
		 Grasas_S: 0.5,
		 Grasas_M: 0,
		 Grasas_P: 0.5,
		 Colesterol: 25,
		 CHO: 0,
		 Na: 0,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 11,
		 Name: 'Pollo claro (pechuga) y Pollo oscuro (muslo)',
		 protein: 7,
		 Grasas_T: 2,
		 Grasas_S: 0.55,
		 Grasas_M: 0.4,
		 Grasas_P: 0.5,
		 Colesterol: 23.5,
		 CHO: 0,
		 Na: 0,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 12,
		 Name: 'Grasas Saturadas (Mantequilla)',
		 protein: 0,
		 Grasas_T: 4.1,
		 Grasas_S: 2.5,
		 Grasas_M: 1.7,
		 Grasas_P: 0.2,
		 Colesterol: 11,
		 CHO: 0,
		 Na: 2,
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 13,
		 Name: 'Grasas Poliinsaturadas (Margarina, Mayonesa, Nueces, Aceite de maiz)',
		 protein: 0,
		 Grasas_T: 4.5,
		 Grasas_S: 0.7,
		 Grasas_M: 1.45,
		 Grasas_P: 2.25,
		 Colesterol: 'Mayonesa: 4',
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 14,
		 Name: 'Aceite de girasol',
		 protein: 0,
		 Grasas_T: 5,
		 Grasas_S: 0.5,
		 Grasas_M: 0.8,
		 Grasas_P: 3.2,
		 Colesterol: 0,
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 15,
		 Name: 'Aceite de girasol',
		 protein: 0,
		 Grasas_T: 5,
		 Grasas_S: 0.5,
		 Grasas_M: 0.8,
		 Grasas_P: 3.2,
		 Colesterol: 0,
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 16,
		 Name: 'Grasas Monoinsaturadas',
		 protein: 0,
		 Grasas_T: 5.1,
		 Grasas_S: 0.75,
		 Grasas_M: 3.55,
		 Grasas_P: 0.5,
		 Colesterol: 0,
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 17,
		 Name: 'Aceite de oliva, aguacate, mani',
		 protein: 0,
		 Grasas_T: 5,
		 Grasas_S: 0.9,
		 Grasas_M: 3,
		 Grasas_P: 1.7,
		 Colesterol: 0,
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},
		{
		 id: 18,
		 Name: 'Mantequilla de mani',
		 protein: 0,
		 Grasas_T: 7.2,
		 Grasas_S: 1.5,
		 Grasas_M: 0,
		 Grasas_P: 2.1,
		 Colesterol: 0,
		 CHO: 0,
		 Na: '< 2',
		 Fibra: 0,
		 Unidad: 1,
		},

		
	];

  return { Teams: Teams };
}());